export const GET_CURRENT_RESOURCE_ITEMS = 'app/GET_CURRENT_RESOURCE_ITEMS';
export const GET_CURRENT_RESOURCE_ITEMS_SUCCESS = 'app/GET_CURRENT_RESOURCE_ITEMS_SUCCESS';
export const GET_CURRENT_RESOURCE_ITEMS_ERROR = 'app/GET_CURRENT_RESOURCE_ITEMS_ERROR';
