export const SET_CURRENT_RESOURCE = 'app/SET_CURRENT_RESOURCE';

export const GET_CRUD_RESOURCE = 'app/GET_CRUD_RESOURCE';
export const GET_CRUD_RESOURCE_SUCCESS = 'app/GET_CRUD_RESOURCE_SUCCESS';
export const GET_CRUD_RESOURCE_ERROR = 'app/GET_CRUD_RESOURCE_ERROR';

export const CREATE_CRUD_RESOURCE = 'app/CREATE_CRUD_RESOURCE';
export const CREATE_CRUD_RESOURCE_SUCCESS = 'app/CREATE_CRUD_RESOURCE_SUCCESS';
export const CREATE_CRUD_RESOURCE_ERROR = 'app/CREATE_CRUD_RESOURCE_ERROR';